name: Release Workflow

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Prepare SpellCoda directory
        run: |
          shopt -s extglob
          mkdir -p topdir
          mv !(topdir) topdir/
          mv topdir SpellCoda

      - name: Get tag name
        id: get_tag
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT

      - name: Create release archive
        run: |
          zip -r ${{ steps.get_tag.outputs.TAG_NAME }}.zip SpellCoda/

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_tag.outputs.TAG_NAME }}
          name: Release ${{ steps.get_tag.outputs.TAG_NAME }}
          generate_release_notes: true
          draft: false
          files: |
            ${{ steps.get_tag.outputs.TAG_NAME }}.zip
